import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — NutriFitLab",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-2xl mx-auto bg-white rounded-2xl shadow-sm border border-gray-100 px-8 py-10">
        <a href="/" className="text-sm text-green-600 hover:text-green-700 transition-colors mb-6 inline-block">
          ← Back to NutriFitLab
        </a>

        <h1 className="text-2xl font-bold text-gray-900 mb-1">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-8">Last updated: April 2026</p>

        <div className="space-y-8 text-sm text-gray-700 leading-relaxed">

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">1. Acceptance of Terms</h2>
            <p>By creating an account or using NutriFitLab, you agree to these Terms of Service. If you do not agree, please do not use the app.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">2. Not Medical Advice</h2>
            <p className="mb-2">NutriFitLab is an AI-assisted tool for general health and fitness information. It is <strong>not</strong> a substitute for professional medical, nutritional, or fitness advice.</p>
            <ul className="space-y-1.5 list-none">
              <li className="flex gap-2"><span className="text-green-600 flex-shrink-0">•</span><span>Always consult a qualified healthcare professional before starting any diet or exercise programme.</span></li>
              <li className="flex gap-2"><span className="text-green-600 flex-shrink-0">•</span><span>Do not use NutriFitLab to diagnose, treat, or manage any medical condition.</span></li>
              <li className="flex gap-2"><span className="text-green-600 flex-shrink-0">•</span><span>If you have injuries, chronic conditions, or specific medical needs, seek guidance from a licensed professional.</span></li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">3. Your Account</h2>
            <ul className="space-y-1.5 list-none">
              <li className="flex gap-2"><span className="text-green-600 flex-shrink-0">•</span><span>You must sign in with a valid Google account. You are responsible for maintaining access to that account.</span></li>
              <li className="flex gap-2"><span className="text-green-600 flex-shrink-0">•</span><span>You are responsible for all activity that occurs under your account.</span></li>
              <li className="flex gap-2"><span className="text-green-600 flex-shrink-0">•</span><span>You must be at least 13 years old to use NutriFitLab.</span></li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">4. Acceptable Use</h2>
            <p className="mb-2">You agree not to:</p>
            <ul className="space-y-1.5 list-none">
              <li className="flex gap-2"><span className="text-green-600 flex-shrink-0">•</span><span>Use NutriFitLab for any unlawful purpose.</span></li>
              <li className="flex gap-2"><span className="text-green-600 flex-shrink-0">•</span><span>Attempt to reverse-engineer, scrape, or abuse the service.</span></li>
              <li className="flex gap-2"><span className="text-green-600 flex-shrink-0">•</span><span>Submit false or misleading information.</span></li>
              <li className="flex gap-2"><span className="text-green-600 flex-shrink-0">•</span><span>Interfere with or disrupt the app or its underlying infrastructure.</span></li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">5. AI-Generated Content</h2>
            <p>Meal plans, workout plans, and chat responses are generated by <strong>Claude AI (Anthropic)</strong>. AI-generated content may be inaccurate, incomplete, or not suitable for your specific situation. You use this content at your own risk. NutriFitLab makes no guarantees about the accuracy or fitness-for-purpose of any AI output.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">6. Intellectual Property</h2>
            <p>The NutriFitLab name, logo, and app design are owned by the NutriFitLab team. You retain ownership of any personal data you provide. AI-generated plans and recipes produced for you are for your personal, non-commercial use only.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">7. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, NutriFitLab and its creators shall not be liable for any indirect, incidental, or consequential damages arising from your use of the app — including any harm from following AI-generated dietary or exercise advice.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">8. Changes to These Terms</h2>
            <p>We may update these Terms from time to time. Continued use of NutriFitLab after changes are posted constitutes your acceptance of the updated Terms. The &quot;Last updated&quot; date at the top of this page reflects when changes were last made.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">9. Contact</h2>
            <p>If you have any questions about these Terms, please contact us at <strong>labsnutrifit@gmail.com</strong>.</p>
          </section>

        </div>
      </div>
    </div>
  );
}
